route:
  group_by: ['alertname', 'job', 'instance', 'severity']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 5h
  receiver: 'Account_name'
  routes:
  - receiver: 'Account_name'
    group_wait: 10s
    matchers:
    - ClientName="Account_name"

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'trouble'
    equal:
      - alertname

receivers:
  - name: 'Account_name'
    webhook_configs:
      - url: 'https://1iagdbxt8d.execute-api.ap-south-1.amazonaws.com/Prod/GraphanaWebhook'
        http_config:
          authorization:
            credentials: NzBkNDIxOTEwMmUyNDQyMzgxZGJhOWQ0YWM4ZTAzNDY=
